apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.ibm_ace_operator.subscriptions.ibmace.name }}
  annotations:
spec:
  {{- toYaml .Values.ibm_ace_operator.subscriptions.ibmace.subscription | nindent 2 }}
